ProvaEstoque/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/novoitem" => "materials#novoitem", as: :novoitem
  get "/matlogs" => "materials#matlogs", as: :matlogs
  get 'home/index'
  root 'home#index'
  resources :usuarios
  resources :materials
  resources :logs
  post "/loginusu" => "usuarios#loginusu", as: :loginusu
  post "/retirar" => "materials#retirar", as: :retirar
  post "/entrar" => "materials#entrar", as: :entrar

end

ProvaEstoque/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ProvaEstoque/app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  belongs_to :material
end

ProvaEstoque/app/models/material.rb
class Material < ApplicationRecord
  has_many :logs
  validates :nome, presence: { message: "Campo Nome é obrigaório !" },
                   uniqueness: { message: "Já existe outro material com este nome !" }
  validates :qnt, presence: { message: "Campo quantidade é obrigaório !" }
  validate :PositiveNumberValidates, if: 'qnt.present?'
  private
    def Nome_Case_Sensitive_Validate
      errors.add("nome", "Nome deve ter primeira letra maiúscula") unless nome =~ /[A-Z].*/
    end
    def PositiveNumberValidates
      errors.add("Qnt", "Quantidade tem que ser positiva") unless qnt>=0
    end
end

ProvaEstoque/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :logs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

ProvaEstoque/app/models/usuario.rb
class Usuario < ApplicationRecord
end

ProvaEstoque/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

      def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
          devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
      end
end

ProvaEstoque/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @materiais = Material.all
  end
end

ProvaEstoque/app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def matlogs
    @logs = Log.where(material: log_params[:matid])
  end
  private
    def log_params
      params.require(:material).permit(:matid)
    end
end

ProvaEstoque/app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]
  
  def new
    @material = Material.new
  end
  def create
    @material = Material.new(material_params)



    logger.debug "--- M #{@material.errors.messages}"
    @material.valid?
    logger.debug "--- M #{@material.errors.messages}"

    @erros = "";
    @ArrErros = Array.new
    @material.errors.messages.each do |message|
      message.each_with_index do |erros,index|
        logger.debug "#{index} --> #{erros}"
        if index==1
          erros.each do |erro|
            logger.debug "------ #{erro}"
            @ArrErros.push(erro)
          end
        end
      end
    end

    if @material.invalid?
      logger.debug "----- ERROR material"
      redirect_to new_material_path(erro: @ArrErros)
    else
      @material.save
      redirect_to @material
    end
    
  end
  def show
    
  end
  def entrar

    @material = Material.find(material_params_estoque[:MatId])
    t = Time.now
    logger.debug "----------------- SEMANA ------ #{t.wday} ---------"
    if t.wday!=0 && t.wday!=6
      if t.hour>9 && t.hour<18
        @material.qnt = @material.qnt.to_i + material_params[:qnt].to_i
        if @material.save
          @log = Log.new(qnt: material_params[:qnt].to_i, user: current_user, material: @material, logtype: "Entrada")
          @log.save
          redirect_to @material      
        end
      else
        redirect_to material_path(@material, error: "003")
      end
    else
      redirect_to material_path(@material, error: "003")
    end
  end
  def retirar

    @material = Material.find(material_params_estoque[:MatId])
    t = Time.now
    logger.debug "----------------- SEMANA ------ #{t.wday} ---------"
    if t.wday!=0 && t.wday!=6
      if t.hour>9 && t.hour<18
        @material.qnt = @material.qnt.to_i - material_params[:qnt].to_i
        if @material.qnt<0
          redirect_to material_path(@material, error: "001")
        else
          if @material.save
            @log = Log.new(qnt: material_params[:qnt].to_i, user: current_user, material: @material, logtype: "Retirada")
            @log.save
            redirect_to @material      
          end
        end
      else
        redirect_to material_path(@material, error: "003")
      end
    else
      redirect_to material_path(@material, error: "003")
    end
  end
  def edit

  end
  def matlogs
    logger.debug 8888888888888888888
    logger.debug "params #{material_params_log[:MatId]}"
    @logs = Log.where(material: material_params_log[:MatId])
    @material = Material.find(material_params_log[:MatId])

  end
  def update
    @material.update(material_params)
    @material.save
    redirect_to @material
  end
  def destroy
    if @log = Log.find_by(material: @material.id)
      redirect_to material_path(@material, error: "002")
    else
      @material.destroy
      redirect_to '/home/index'
    end
  end
  private
    def set_material
      @material = Material.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:nome, :qnt)
    end
    def material_params_estoque
      params.require(:material).permit(:MatId, :qnt)
    end
    def material_params_log
      params.permit(:MatId)
    end

end

ProvaEstoque/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def loginusu
    @usuario = Usuario.find_by(login: user_params[:login], senha: user_params[:senha])
    logger.debug "-------------- RESULT ----------------"
    if @usuario
      logger.debug "-------------- USUARIO EXISTE ----------------"
    else
      logger.debug "-------------- USUARIO NAO EXITE ----------------"
    end
  end

  def new
    @usuario = Usuario.new
  end

  def create
    if user_params_create[:senha]==user_params_create[:password_confirmation]
      @usuario = Usuario.new
      @usuario.login = user_params_create[:login]
      @usuario.senha = user_params_create[:senha]
      @usuario.save

      redirect_to home_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:usuario).permit(:login, :senha)
    end

    def user_params_create
      params.require(:usuario).permit(:login, :senha, :password_confirmation)
    end
end

ProvaEstoque/app/helpers/application_helper.rb
module ApplicationHelper
end

ProvaEstoque/app/views/home/index.html.erb
<h1>Material</h1>
<% if @materiais.length!=0 %>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Estoque</th>
      <th>Log</th>
    </tr>
  </thead>
  <tbody>
    <% @materiais.each do |material| %>
      <tr>
        <td><%= material.id %></td>
        <td><%= link_to material.nome , material_path(material) %></td>
        <td><%= material.qnt %></td>
        <td><%= link_to 'Log', matlogs_path(MatId: material.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h6>Não há itens cadastrados</h6>
<% end %>
<%= link_to new_material_path do %>
  <input type="button" class="btn btn-default" value="Novo Material">
<% end %>

ProvaEstoque/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProvaEstoque</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap.min.css' , 'bootstrap-theme.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap.min.js' %>
  </head>

  <body>


  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logado como <strong><%= current_user.name %></strong>.
      <%= link_to 'Editar Usuário', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Cadastrar", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

ProvaEstoque/app/views/materials/_form.html.erb
<%= bootstrap_form_for(material) do |f| %>
  <%= f.text_field :nome %>
  <%= f.number_field :qnt %>
  <%= f.submit %>
<% end %>

ProvaEstoque/app/views/materials/_formedit.html.erb
<%= bootstrap_form_for(material) do |f| %>
  <%= f.text_field :nome %>
  <%= f.hidden_field :qnt %>
  <%= f.submit %>
<% end %>

ProvaEstoque/app/views/materials/edit.html.erb
<h1>Editar <%= @material.nome %></h1>
<%= render 'formedit', material: @material %>
<%= link_to '/home/index' do %>
  <input type="button" class="btn btn-default" value="Voltar">
<% end %>

ProvaEstoque/app/views/materials/matlogs.html.erb
<h1>Log de <%= @material.nome %></h1>
<% if @logs.length!=0 %>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Usuario</th>
      <th>Material</th>
      <th>Tipo</th>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.id %></td>
        <td><%= log.user.name %></td>
        <td><%= log.qnt %></td>
        <td><%= log.logtype %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h6>Não há itens cadastrados</h6>
<% end %>

<%= link_to '/home/index' do %>
  <input type="button" class="btn btn-default" value="Voltar">
<% end %>

ProvaEstoque/app/views/materials/new.html.erb
<h1>Novo Material</h1>
<div class="alert alert-danger" id="DIV_alert_Error" role="alert" style="display:none">
  <div id="Msg_Alert_Error"></div>
</div>
<%= render 'form', material: @material %>

<%= link_to '/home/index' do %>
  <input type="button" class="btn btn-default" value="Voltar">
<% end %>
<% if params[:erro] != nil %>
  <% if params[:erro].length != 0 %>
  <script type="text/javascript">
      $('#Msg_Alert_Error').html("<strong>Atenção! </strong>");
      <% params[:erro].each do |err| %>
        <% logger.debug "---- NEW -- #{err}" %>
        $('#Msg_Alert_Error').append("<br><%= err %>");
      <% end %>
      $('#DIV_alert_Error').show();
      setTimeout(function(){ $('#DIV_alert_Error').hide(); }, 10000);
  </script>
  <% end %>
<% end %>

ProvaEstoque/app/views/materials/show.html.erb
<h1>SHOW material</h1>
<h2>
  <%= @material.nome %>
  <div style="font-size: 15px;font-weight: normal;">
    (
    <%= link_to 'Editar' , edit_material_path %>
    <%= link_to 'Deletar', @material, method: :delete, data: { confirm: 'Realmente deseja deletar?' } %>
    )
  </div>
</h2>
<p>Estoque: <%= @material.qnt %>
</p>

<div class="alert alert-danger" id="DIV_alert_Red_AddTipoUsu" role="alert" style="display:none">
  <div id="Alert_Red_AddTipoUsu"></div>
</div>
<% if params[:error]=='001' %>
  <script type="text/javascript">
      $('#DIV_alert_Red_AddTipoUsu').show();
      $('#Alert_Red_AddTipoUsu').html("<strong>Atenção! </strong>Valor so estoque não pode ser negativo.<br> Máximo valor para retirada: <%= @material.qnt %>");
      setTimeout(function(){ $('#DIV_alert_Red_AddTipoUsu').hide(); }, 10000);
  </script>
<% end %>
<% if params[:error]=='002' %>
  <script type="text/javascript">
      $('#DIV_alert_Red_AddTipoUsu').show();
      $('#Alert_Red_AddTipoUsu').html("<strong>Atenção! </strong>Material não pode ser apagado.<br> Há registros de log em seu nome");
      setTimeout(function(){ $('#DIV_alert_Red_AddTipoUsu').hide(); }, 10000);
  </script>
<% end %>
<% if params[:error]=='003' %>
  <script type="text/javascript">
      $('#DIV_alert_Red_AddTipoUsu').show();
      $('#Alert_Red_AddTipoUsu').html("<strong>Atenção! </strong>Estoque não pode ser alterado.<br> Acesso garantido apenas de segunda a sexta de 9h as 18h.");
      setTimeout(function(){ $('#DIV_alert_Red_AddTipoUsu').hide(); }, 10000);
  </script>
<% end %>
<button class="btn btn-default" data-toggle="collapse" data-target="#demo">Controle do Estoque</button>
<div id="demo" class="collapse">
  <div class="panel panel-default">
    <div class="panel-body">
      <b>Entrada</b>
      <%= bootstrap_form_for(@material, layout: :inline, url: entrar_path, :method => :POST )do |f| %>
            <%= f.number_field :qnt, hide_label: true, value: 0  %>
            <%= f.hidden_field :MatId, hide_label: true, value: @material.id  %>
            <%= f.submit "Entrar", class: "btn btn-default" %>
      <% end %>

      <b>Retirada</b>
      <%= bootstrap_form_for(@material, layout: :inline, url: retirar_path, :method => :POST ) do |f| %>
            <%= f.number_field :qnt, hide_label: true, value: 0 %>
            <%= f.hidden_field :MatId, hide_label: true, value: @material.id  %>
            <%= f.submit "Retirar", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>


<%= link_to '/home/index' do %>
  <input type="button" class="btn btn-default" value="Voltar">
<% end %>

ProvaEstoque/app/views/usuarios/_form.html.erb
<%= bootstrap_form_for(usuario) do |f| %>
  <%= f.text_field :login %>
  <%= f.password_field :senha %>
  <%= f.password_field :password_confirmation, label: "Confirm Password", value: params.permit(:password_confirmation)[:password_confirmation] %>
  <%= f.submit %>
<% end %>

ProvaEstoque/app/views/usuarios/new.html.erb
  <h1>Cadastro Usuario</h1>
  <%= render 'form', usuario: @usuario %>